- name: Configure nginx
  tags: web
  become: true
  hosts: servers
  roles:
    - sedovandrew.nginx

- hosts: servers
  become: true
  roles:
     - role: pacemaker
     - role: iscsi-client

- hosts: iscsi
  become: true
  roles:
     - role: iscsi-target
